name: src
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.12
  - pip==21.3.1
  - pip:
      - matplotlib==3.5.1
      - numpy==1.22.0
      - pandas==1.3.5
      - scipy==1.7.3
      - twine==3.8.0
